apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mypythonflaskdemo
  name: mypythonflaskdemo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mypythonflaskdemo
  template:
    metadata:
      labels:
        app: mypythonflaskdemo
    spec:
      containers:
      - image: "balaji2018/my-images:1"
        name: flaskdemo-pod
        ports:
          - name: http
            containerPort: 9001
            protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: mypythonflaskdemo
spec:
  type: NodePort
  ports:
  - port: 9001
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app: mypythonflaskdemo
